### PR TITLE
Latest Azure icons

### PR DESCRIPTION
**Pull request by phatcher**

### CODE REVIEW

**Review by Potherca — APPROVED** [review]

**Comment by travisnielsen** [comment]
Curious to know if there's a timeline for getting this merged.

**Comment by Potherca** [comment]
@travisnielsen Thank you for pointing out that this had stalled!

The original agreement was that (at least) 2 developers should review changes before merging.

As most other original maintainer have a lot on their plate, I am merging this without the extra review.

@phatcher My apologies for making you wait for such a long time. You hard work and dilligence in supporting this project is very much appreciated. Thank you again for your contributions!

**Comment by phatcher** [comment]
@Potherca  Only issue is I think some of the icons are corrupted - and I don't know enough about svg to diagnose what is going on see https://github.com/plantuml-stdlib/Azure-PlantUML/blob/master/AzureSymbols.md

* AzurePowerBIEmbedded
* AzureServiceEndpoint
* AzureSubnet
* AzureVirtualNetworkPeering

It's probably systemic or down to the original icons but as I said I can't really help much.

**Comment by Potherca** [comment]
No worries, I'll take a look. Thanks for make the separate ticket! 👍

**Pull request merged**
